# ROS1-ROS2 Bridge Configuration
# 갭 측정 시스템용 브리지 설정

bridge:
  # 브리지 모드 설정
  mode: "static"  # static 또는 dynamic
  
  # 커스텀 메시지 매핑
  custom_messages:
    - "gap_detection_msgs/SectionArrival"
    - "gap_detection_msgs/MeasurementCommand"
    - "gap_detection_msgs/MeasurementResult"
    - "gap_detection_msgs/ProcessComplete"
    - "robot_coordination_msgs/SystemStatus"
    - "robot_coordination_msgs/RobotState"
    - "robot_coordination_msgs/CoordinationCommand"
  
  # 서비스 매핑
  custom_services:
    - "gap_detection_msgs/StartMeasurement"
    - "gap_detection_msgs/StopMeasurement"
    - "robot_coordination_msgs/GetSystemStatus"
    - "robot_coordination_msgs/SetRobotState"
  
  # 토픽 매핑
  topic_mapping:
    # ROS1 → ROS2
    "/gap_detection/section_arrival": "/gap_detection/section_arrival"
    "/gap_detection/measurement_command": "/gap_detection/measurement_command"
    "/robot_coordination/system_status": "/robot_coordination/system_status"
    
    # ROS2 → ROS1
    "/gap_detection/measurement_result": "/gap_detection/measurement_result"
    "/gap_detection/process_complete": "/gap_detection/process_complete"
    "/robot_coordination/robot_state": "/robot_coordination/robot_state"
  
  # 네트워크 설정
  network:
    ros1_master_uri: "http://localhost:11311"
    ros2_domain_id: 0
    
  # 로깅 설정
  logging:
    level: "info"
    log_file: "/workspace/logs/bridge.log"
